apply from: 'gradle/dependency-versions.gradle'

allprojects {
    group = findProperty('group') ?: 'io.github.brody-0125'
    version = findProperty('version') ?: '1.0.0'
    repositories { mavenCentral() }
}
subprojects { sub ->
    if (sub.path == ':plugin') {
        return
    }
    apply plugin: 'java-library'
    java { toolchain { languageVersion = JavaLanguageVersion.of(17) } }
    tasks.withType(Test).configureEach { useJUnitPlatform() }
}
