pluginManagement {
    plugins {
        id 'com.vanniktech.maven.publish' version '0.30.0'
    }
    includeBuild('plugin')
    repositories { mavenLocal(); gradlePluginPortal(); mavenCentral() }
}
rootProject.name = 'spring-test-isolation'
include 'runtime', 'maven-plugin', 'verification', 'verification-peer'

includeBuild('plugin') {
    dependencySubstitution {
        substitute(module('io.github.brody-0125:spring-test-isolation-runtime')).using(project(':runtime'))
    }
}
