dependencies {
    testImplementation project(':runtime')
    testImplementation "redis.clients:jedis:${versions.jedis}"
    testImplementation platform("org.springframework.boot:spring-boot-dependencies:${versions.springBoot}")
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-redis'
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation "org.flywaydb:flyway-core:${versions.flyway}"
    testImplementation "org.flywaydb:flyway-database-postgresql:${versions.flyway}"
    testImplementation "org.flywaydb:flyway-mysql:${versions.flyway}"
    testRuntimeOnly "org.postgresql:postgresql:${versions.postgresqlJdbc}"
    testRuntimeOnly "com.mysql:mysql-connector-j:${versions.mysqlJdbc}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${versions.junitPlatform}"
    testImplementation "org.testng:testng:${versions.testng}"
    testImplementation "io.kotest:kotest-runner-junit5:${versions.kotest}"
    testImplementation "io.kotest.extensions:kotest-extensions-spring:${versions.kotestSpring}"
}
