package workflow;

import io.github.brody0125.springtestisolation.ClassBoundary;
import io.github.brody0125.springtestisolation.WorkerStore;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.data.redis.core.script.DefaultRedisScript;
import org.springframework.data.redis.listener.ChannelTopic;
import org.springframework.data.redis.listener.RedisMessageListenerContainer;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.*;

/** Test-only outbox fixture; not a production messaging implementation. */
@SpringBootConfiguration
@EnableAutoConfiguration
public class WorkflowApplication {
    @Bean Flow flow(JdbcTemplate jdbc, StringRedisTemplate redis, WorkerStore store, PlatformTransactionManager tx) {
        return new Flow(jdbc, redis, store, tx);
    }

    @RestController
    static class Api {
        final Flow flow;
        Api(Flow flow) { this.flow = flow; }
        @PostMapping("/orders") long order(@RequestParam(name = "rollback", defaultValue = "false") boolean rollback) {
            return flow.create(rollback);
        }
        @GetMapping("/orders/{id}") String read(@PathVariable("id") long id) {
            return flow.redis.opsForValue().get("cache:" + id);
        }
    }

    static class Flow implements ClassBoundary, AutoCloseable {
        final JdbcTemplate jdbc;
        final StringRedisTemplate redis;
        final WorkerStore store;
        final TransactionTemplate tx;
        final ExecutorService executor = Executors.newSingleThreadExecutor();
        final BlockingQueue<String> messages = new LinkedBlockingQueue<>();
        final RedisMessageListenerContainer listener = new RedisMessageListenerContainer();
        final DefaultRedisScript<Long> unlock = new DefaultRedisScript<>(
                "if redis.call('get',KEYS[1]) == ARGV[1] then return redis.call('del',KEYS[1]) else return 0 end", Long.class);
        volatile boolean accepting;
        CountDownLatch releaseLate;
        Future<?> late;
        int processed;

        Flow(JdbcTemplate jdbc, StringRedisTemplate redis, WorkerStore store, PlatformTransactionManager manager) {
            this.jdbc = jdbc; this.redis = redis; this.store = store; this.tx = new TransactionTemplate(manager);
            jdbc.execute("CREATE TABLE IF NOT EXISTS orders (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner text NOT NULL)");
            jdbc.execute("CREATE TABLE IF NOT EXISTS order_items (order_id bigint REFERENCES orders(id), sku text, quantity integer, PRIMARY KEY(order_id,sku))");
            jdbc.execute("CREATE TABLE IF NOT EXISTS outbox (id bigint PRIMARY KEY REFERENCES orders(id), sent boolean NOT NULL DEFAULT false)");
            jdbc.execute("CREATE SCHEMA IF NOT EXISTS projection");
            jdbc.execute("CREATE TABLE IF NOT EXISTS projection.receipts (event_id bigint PRIMARY KEY REFERENCES orders(id))");
            jdbc.execute("CREATE TABLE IF NOT EXISTS projection.totals (order_id bigint PRIMARY KEY REFERENCES orders(id), quantity integer NOT NULL)");
            listener.setConnectionFactory(redis.getConnectionFactory());
            listener.addMessageListener((message, pattern) -> messages.add(new String(message.getBody(), StandardCharsets.UTF_8)),
                    new ChannelTopic(store.channel("orders:projected")));
            listener.afterPropertiesSet();
        }

        long create(boolean rollback) {
            String token = UUID.randomUUID().toString();
            if (!Boolean.TRUE.equals(redis.opsForValue().setIfAbsent("lock:order", token, Duration.ofSeconds(30))))
                throw new ResponseStatusException(HttpStatus.CONFLICT, "locked");
            try {
                return tx.execute(status -> {
                    Long id = jdbc.queryForObject("INSERT INTO orders(owner) VALUES (?) RETURNING id", Long.class, store.namespace);
                    jdbc.update("INSERT INTO order_items VALUES (?, 'same-sku', 3)", id);
                    jdbc.update("INSERT INTO outbox(id) VALUES (?)", id);
                    if (rollback) throw new ResponseStatusException(HttpStatus.CONFLICT, "INJECTED_ROLLBACK");
                    return id;
                });
            } finally { redis.execute(unlock, List.of("lock:order"), token); }
        }

        void publish(boolean failAfterEnqueue) {
            for (Long id : jdbc.queryForList("SELECT id FROM outbox WHERE NOT sent ORDER BY id", Long.class)) {
                redis.opsForList().rightPush("orders:queue", id.toString());
                if (failAfterEnqueue) throw new IllegalStateException("INJECTED_AFTER_ENQUEUE");
                jdbc.update("UPDATE outbox SET sent=true WHERE id=?", id);
            }
        }

        synchronized Future<?> consume(boolean failAfterCommit) {
            if (!accepting) throw new IllegalStateException("quiescing");
            return executor.submit(() -> {
                String next;
                // Keep the head until DB, cache and notification succeed. One consumer per fixture.
                while ((next = redis.opsForList().index("orders:queue", 0)) != null) {
                    long id = Long.parseLong(next);
                    tx.executeWithoutResult(status -> {
                        if (jdbc.update("INSERT INTO projection.receipts VALUES (?) ON CONFLICT DO NOTHING", id) == 1) {
                            jdbc.update("INSERT INTO projection.totals SELECT order_id,sum(quantity) FROM order_items WHERE order_id=? GROUP BY order_id", id);
                            processed++;
                        }
                    });
                    if (failAfterCommit) throw new IllegalStateException("INJECTED_AFTER_PROJECTION_COMMIT");
                    String owner = jdbc.queryForObject("SELECT owner FROM orders WHERE id=?", String.class, id);
                    int total = jdbc.queryForObject("SELECT quantity FROM projection.totals WHERE order_id=?", Integer.class, id);
                    redis.opsForValue().set("cache:" + id, owner + total);
                    redis.convertAndSend(store.channel("orders:projected"), owner + id);
                    redis.opsForList().leftPop("orders:queue");
                }
            });
        }

        synchronized void scheduleLate() throws Exception {
            if (!accepting) throw new IllegalStateException("quiescing");
            releaseLate = new CountDownLatch(1);
            CountDownLatch started = new CountDownLatch(1);
            late = executor.submit(() -> {
                started.countDown();
                try {
                    if (!releaseLate.await(8, TimeUnit.SECONDS)) throw new IllegalStateException("Boundary did not release pending work");
                    jdbc.update("INSERT INTO orders(id,owner) VALUES (900, 'late')");
                    jdbc.update("INSERT INTO order_items VALUES (900,'late-sku',1)");
                    jdbc.update("INSERT INTO outbox(id) VALUES (900)");
                    redis.opsForValue().set("late:key", "dirty");
                    redis.opsForList().rightPush("orders:queue", "900");
                    messages.add("late-local");
                } catch (InterruptedException e) { Thread.currentThread().interrupt(); throw new IllegalStateException(e); }
            });
            if (!started.await(5, TimeUnit.SECONDS)) throw new IllegalStateException("Late work did not start");
        }

        public void quiesce() throws Exception {
            synchronized (this) { accepting = false; }
            if (releaseLate != null) releaseLate.countDown();
            if (late != null) {
                late.get(5, TimeUnit.SECONDS);
                System.out.println("WORKFLOW drained worker=" + System.getProperty("org.gradle.test.worker"));
                late = null;
            }
            if (!executor.isShutdown()) executor.submit(() -> {}).get(5, TimeUnit.SECONDS);
            listener.stop();
        }
        public void reset() { messages.clear(); processed = 0; releaseLate = null; }
        public void resume() { listener.start(); accepting = true; }
        public void close() throws Exception {
            quiesce(); listener.destroy(); executor.shutdown();
            if (!executor.awaitTermination(5, TimeUnit.SECONDS)) throw new IllegalStateException("Consumer leaked");
            jdbc.update("INSERT INTO orders(id,owner) VALUES (901,'destroy')");
            // Spring stops SmartLifecycle connection factories before bean destruction.
            // Use the worker-owned connection to deliberately exercise post-close cleanup.
            try (var connection = store.redis()) { connection.set("destroy:key", "dirty"); }
            System.out.println("WORKFLOW destroyed worker=" + System.getProperty("org.gradle.test.worker"));
        }
    }
}
